
run1.mass:
	g++ -std=c++17 ./1.mass.cpp -o ./build/1.mass -g && ./build/1.mass
	
run2.struct:
	g++ -std=c++17 ./2.struct.cpp -o ./build/2.struct -g && ./build/2.struct
	
run3.square:
	g++ -std=c++17 ./3.square.cpp -o ./build/3.square -g && ./build/3.square

run4.sredpoint:
	g++ -std=c++17 ./4.sredpoint.cpp -o ./build/4.sredpoint -g && ./build/4.sredpoint

run5.crosslines:
	g++ -std=c++17 ./5.crosslines.cpp -o ./build/5.crosslines -g && ./build/5.crosslines



	