
run_1.list:
	g++ -std=c++17 ./1.list.cpp -o ./build/1.list -g && ./build/1.list

run_2.graf:
	g++ -std=c++17 ./2.graf.cpp -o ./build/2.graf -g && ./build/2.graf

run_3.file_in_out:
	g++ -std=c++17 ./3.file_in_out.cpp -o ./build/3.file_in_out -g && ./build/3.file_in_out
