
run_1.op-overload:
	g++ -std=c++17 ./1.op_overload.cpp -o ./build/1.op_overload -g && ./build/1.op_overload
run_2.matrixes:
	g++ -std=c++17 ./2.matrixes.cpp -o ./build/2.matrixes -g && ./build/2.matrixes



	