version: '3.7'

volumes:
  mysql-vl:

networks:
  default:
    driver: bridge

services:
  mysql-server:
    image: mysql:8
    restart: unless-stopped
    container_name: mysql-server
    ports:
      - 33060:3306
    volumes:
      - mysql-vl:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_LOGIN=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - default
  docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    ports:
      - "8095:80"
    environment:
      - PMA_HOST=mysql-server
      # - PMA_PORT=3306
    networks:
      - default
    depends_on:
      - mysql-server