
run1.one:
	g++ -std=c++17 ./1.one.cpp -o ./build/1.one -g && ./build/1.one

run1.1.one:
	g++ -std=c++17 ./1.1.one.cpp -o ./build/1.1.one -g && ./build/1.1.one
	
run2.class:
	g++ -std=c++17 ./2.class.cpp -o ./build/2.class -g && ./build/2.class

run3.okr:
	g++ -std=c++17 ./3.okr.cpp -o ./build/3.okr -g && ./build/3.okr

run4.nasled:
	g++ -std=c++17 ./4.nasled.cpp -o ./build/4.nasled -g && ./build/4.nasled
	
run5.virtual:
	g++ -std=c++17 ./5.virtual.cpp -o ./build/5.virtual -g && ./build/5.virtual
run6.virtual:
	g++ -std=c++17 ./6.virtual2.cpp -o ./build/6.virtual2 -g && ./build/6.virtual2
	


	