
run1.one:
	g++ -std=c++17 ./1.one.cpp -o ./build/1.one -g && ./build/1.one

run1.1.one:
	g++ -std=c++17 ./1.1.one.cpp -o ./build/1.1.one -g && ./build/1.1.one
	
run2.class:
	g++ -std=c++17 ./2.class.cpp -o ./build/2.class -g && ./build/2.class
	



	